/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "error": "#ff716c",
        "on-error": "#490006",
        "on-secondary-container": "#e1ffec",
        "on-background": "#dbe6fe",
        "on-secondary-fixed": "#00452d",
        "tertiary-fixed": "#f8a010",
        "error-dim": "#d7383b",
        "background": "#040e1f",
        "on-error-container": "#ffa8a3",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#15263f",
        "tertiary": "#ffb148",
        "surface-tint": "#3bbffa",
        "primary-fixed": "#2db7f2",
        "outline": "#6b768b",
        "surface-container": "#0b1a2f",
        "surface-container-low": "#061326",
        "tertiary-fixed-dim": "#e79400",
        "tertiary-dim": "#e79400",
        "inverse-surface": "#f9f9ff",
        "secondary": "#69f6b8",
        "secondary-container": "#006c49",
        "on-secondary": "#005a3c",
        "tertiary-container": "#f8a010",
        "on-tertiary": "#573500",
        "on-primary-container": "#002b3d",
        "primary": "#3bbffa",
        "secondary-fixed-dim": "#58e7ab",
        "on-surface-variant": "#a0abc2",
        "on-primary": "#00374d",
        "on-tertiary-fixed-variant": "#563400",
        "surface-dim": "#040e1f",
        "on-tertiary-fixed": "#2a1700",
        "outline-variant": "#3d485c",
        "primary-dim": "#05a9e3",
        "surface-variant": "#15263f",
        "surface-bright": "#1b2c47",
        "primary-fixed-dim": "#05a9e3",
        "inverse-on-surface": "#4a5569",
        "on-primary-fixed": "#00121d",
        "secondary-dim": "#58e7ab",
        "on-surface": "#dbe6fe",
        "on-secondary-fixed-variant": "#006544",
        "primary-container": "#22b1ec",
        "inverse-primary": "#00668b",
        "surface-container-high": "#102036",
        "on-tertiary-container": "#4a2c00",
        "error-container": "#9f0519",
        "on-primary-fixed-variant": "#003a50",
        "surface": "#040e1f",
        "secondary-fixed": "#69f6b8",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "Courier New", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

